# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('deceased', models.BooleanField(default=False)),
                ('prenom', models.CharField(blank=True, max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('postnom', models.CharField(blank=True, max_length=128)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MASCULIN', 'M'), ('FEMININ', 'F')], default='MASCULIN', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
