# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_models_person_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MASCULIN', 'M'), ('FEMININ', 'F')], default='MASCULIN', max_length=1),
        ),
    ]
