# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_models_person_edited2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='person.Person')),
                ('id_num', models.CharField(max_length=13, unique=True)),
                ('seq_num', models.CharField(default=b'5844', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='citizen',
            field=models.BooleanField(default=True),
        ),
    ]
